export const shipmentStatus = {
  1: "Awb Assigned",
  2: "Label Generated",
  3: "Pickup Scheduled/Generated",
  4: "Pickup Queued",
  5: "Manifest Generated",
  6: "Shipped",
  7: "Delivered",
  8: "Cancelled",
  9: "RTO Initiated",
  10: "RTO Delivered",
  11: "Pending",
  12: "Lost",
  13: "Pickup Error",
  14: "RTO Acknowledged",
  15: "Pickup Rescheduled",
  16: "Cancellation Requested",
  17: "Out For Delivery",
  18: "In Transit",
  19: "Out For Pickup",
  20: "Pickup Exception",
  21: "Undelivered",
  22: "Delayed",
};
